#!/bin/bash

# Read the file line by line and store the third line in a variable
count=1
while IFS= read -r line
do
  if [ $count -eq 3 ]; then
    echo "$line"
    break
  fi
  ((count++))
done < "iacta"
